### ISSUE TITLE
Typography Guide

### ISSUE THREAD

**Issue by jlooper** [jlooper/curriculum-template#2]
This is a short document describing the typography and iconography for our lessons. 

**Typography**

# Lesson Topic

### Tasks

> Special callouts

Use descriptions for code blocks to enable formatting (` ```javascript`)
 
```javascript
code blocks
``` 

---

**Icons**

✅ Knowledge Check

🚀 Challenge

🎓 Lexicon/Jargon Descriptions

🧮  Show Me the Math

💁  'Trivia' or interesting supplemental content

**Comment by jimbobbennett** [comment]
I've been using 💁, the emoji for a gender neutral information desk attendant when there's a small section of additional information that's of interest but not important.

For example, in a section introducing telemetry, I've added the following:

💁 One of the earliest telemetry devices was invented in France in 1874 and sent real-time weather and snow depths from Mont Blanc to Paris. It used physical wires as wireless technologies were not available at the time.

This is interesting, but not important, hence the information desk attendant emoji.

**Comment by jlooper** [comment]
that's cool! let's add it in.

**Comment by jlooper** [comment]
Moving this to a wiki
